2025148532 이우화 파이썬프로그래밍 과제 11주

In [1]:
# CODE 셀 1
import numpy as np

In [28]:
# CODE 셀 2
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b[0])

[1 2 3 4 5 6]
[1 2 3 4]


In [27]:
# CODE 셀 3
a = np.array([1, 2, 3])
print("np.array:", a)

print("np.zeros:", np.zeros(2))
print("np.ones:", np.ones(2))
print("np.empty:", np.empty(2))
print("np.arange(4):", np.arange(4))
print("np.arange(2, 9, 2):", np.arange(2, 9, 2))
print("np.linspace:", np.linspace(0, 10, num=5))

x = np.ones(2, dtype=np.int64)
print("dtype 지정:", x)

np.array: [1 2 3]
np.zeros: [0. 0.]
np.ones: [1. 1.]
np.empty: [1. 1.]
np.arange(4): [0 1 2 3]
np.arange(2, 9, 2): [2 4 6 8]
np.linspace: [ 0.   2.5  5.   7.5 10. ]
dtype 지정: [1 1]


In [26]:
# CODE 셀 4
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print("정렬:", np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("연결(1D):", np.concatenate((a, b)))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print("연결(2D):", np.concatenate((x, y), axis=0))

정렬: [1 2 3 4 5 6 7 8]
연결(1D): [1 2 3 4 5 6 7 8]
연결(2D): [[1 2]
 [3 4]
 [5 6]]


In [25]:
# CODE 셀 5
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print("차원 수(ndim):", array_example.ndim)
print("전체 요소 수(size):", array_example.size)
print("배열 형태(shape):", array_example.shape)

차원 수(ndim): 3
전체 요소 수(size): 24
배열 형태(shape): (3, 2, 4)


In [24]:
# CODE 셀 6
a = np.arange(6)
print("원본:", a)

b = a.reshape(3, 2)
print("reshape(3, 2):\\n", b)

c = np.reshape(a, newshape=(1, 6), order='C')
print("reshape(1, 6):", c)

원본: [0 1 2 3 4 5]
reshape(3, 2):\n [[0 1]
 [2 3]
 [4 5]]
reshape(1, 6): [[0 1 2 3 4 5]]


In [23]:
# CODE 셀 7
a = np.array([1, 2, 3, 4, 5, 6])
print("원본 shape:", a.shape)

row_vector = a[np.newaxis, :]
print("row vector shape:", row_vector.shape)

col_vector = a[:, np.newaxis]
print("col vector shape:", col_vector.shape)

b = np.expand_dims(a, axis=1)
print("expand_dims (axis=1) shape:", b.shape)

c = np.expand_dims(a, axis=0)
print("expand_dims (axis=0) shape:", c.shape)

원본 shape: (6,)
row vector shape: (1, 6)
col vector shape: (6, 1)
expand_dims (axis=1) shape: (6, 1)
expand_dims (axis=0) shape: (1, 6)


In [22]:
# CODE 셀 8
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("a < 5 인 요소들:", a[a < 5])

five_up = (a >= 5)
print("5 이상인 요소들:", a[five_up])

divisible_by_2 = a[a % 2 == 0]
print("짝수 요소들:", divisible_by_2)

c = a[(a > 2) & (a < 11)]
print("조건 결합(&):", c)

five_up = (a > 5) | (a == 5)
print("조건 결합(|):\\n", five_up)

2
[1 2]
[2 3]
[2 3]
a < 5 인 요소들: [1 2 3 4]
5 이상인 요소들: [ 5  6  7  8  9 10 11 12]
짝수 요소들: [ 2  4  6  8 10 12]
조건 결합(&): [ 3  4  5  6  7  8  9 10]
조건 결합(|):\n [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
# CODE 셀 9
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print("조건 만족 인덱스:", b)

list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print("조건 만족 실제 값:", a[b])

not_there = np.nonzero(a == 42)
print("없는 값 찾기:", not_there)

조건 만족 인덱스: (array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
조건 만족 실제 값: [1 2 3 4]
없는 값 찾기: (array([], dtype=int64), array([], dtype=int64))


In [20]:
# CODE 셀 10
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print(arr1)

a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
print("vstack:\\n", np.vstack((a1, a2)))
print("hstack:\\n", np.hstack((a1, a2)))

x = np.arange(1, 25).reshape(2, 12)
print("hsplit(3):\\n", np.hsplit(x, 3))
print("hsplit((3, 4)):\\n", np.hsplit(x, (3, 4)))

[4 5 6 7 8]
vstack:\n [[1 1]
 [2 2]
 [3 3]
 [4 4]]
hstack:\n [[1 1 3 3]
 [2 2 4 4]]
hsplit(3):\n [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
hsplit((3, 4)):\n [array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [19]:
# CODE 셀 11
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1[0] = 99
print("b1 수정 후 b1:", b1)
print("b1 수정 후 a:\\n", a) # View이므로 a도 함께 변경됨

# Copy 사용
b2 = a.copy()

b1 수정 후 b1: [99  2  3  4]
b1 수정 후 a:\n [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# CODE 셀 12
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print("더하기:", data + ones)
print("빼기:", data - ones)
print("곱하기:", data * data)
print("나누기:", data / data)

a = np.array([1, 2, 3, 4])
print("sum:", a.sum())

b = np.array([[1, 1], [2, 2]])
print("sum(axis=0):", b.sum(axis=0))
print("sum(axis=1):", b.sum(axis=1))

더하기: [2 3]
빼기: [0 1]
곱하기: [1 4]
나누기: [1. 1.]
sum: 10
sum(axis=0): [3 3]
sum(axis=1): [2 4]


In [17]:
# CODE 셀 13
data = np.array([1.0, 3.0])
print(data * 1.6)

[1.6 4.8]


In [14]:
# CODE 셀 14
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())
print(a.min(axis=0))

3
1
6
4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [13]:
# CODE 셀 15
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

print(data.max())
print(data.min())
print(data.sum())

data = np.array([[1, 2], [5, 3], [4, 6]])
print(data.max(axis=0))
print(data.max(axis=1))

2
[[3 4]
 [5 6]]
[1 3]
6
1
21
[5 6]
[2 5 6]


In [12]:
# CODE 셀 16
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print("data + ones:\\n", data + ones)

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print("data + ones_row:\\n", data + ones_row)

print("np.ones((4, 3, 2)):\\n", np.ones((4, 3, 2)))

data + ones:\n [[2 3]
 [4 5]]
data + ones_row:\n [[2 3]
 [4 5]
 [6 7]]
np.ones((4, 3, 2)):\n [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [11]:
# CODE 셀 17
rng = np.random.default_rng()
print("난수 3개:", rng.random(3))

print("정수 난수:\\n", rng.integers(5, size=(2, 4)))

난수 3개: [0.84602009 0.59831929 0.86691362]
정수 난수:\n [[0 0 2 2]
 [1 1 4 3]]


In [10]:
# CODE 셀 18
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print("고유값:", unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print("고유값의 첫 등장 인덱스:", indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print("고유값 등장 횟수:", occurrence_count)

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
print("2D 고유값:", np.unique(a_2d))
print("2D 고유행(axis=0):\\n", np.unique(a_2d, axis=0))

고유값: [11 12 13 14 15 16 17 18 19 20]
고유값의 첫 등장 인덱스: [ 0  2  3  4  5  6  7 12 13 14]
고유값 등장 횟수: [3 2 2 2 1 1 1 1 1 1]
2D 고유값: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D 고유행(axis=0):\n [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# CODE 셀 19
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.reshape(2, 3))
print(data.reshape(3, 2))

arr = np.arange(6).reshape((2, 3))
print("원본:\\n", arr)
print("전치(transpose):\\n", arr.transpose())
print("전치(T):\\n", arr.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
원본:\n [[0 1 2]
 [3 4 5]]
전치(transpose):\n [[0 3]
 [1 4]
 [2 5]]
전치(T):\n [[0 3]
 [1 4]
 [2 5]]


In [8]:
# CODE 셀 20
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('Reversed Array:', np.flip(arr))

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("전체 뒤집기:\\n", np.flip(arr_2d))
print("행 단위 뒤집기:\\n", np.flip(arr_2d, axis=0))
print("열 단위 뒤집기:\\n", np.flip(arr_2d, axis=1))

arr_2d[1] = np.flip(arr_2d[1])
print("특정 행만 뒤집기:\\n", arr_2d)

arr_2d[:,1] = np.flip(arr_2d[:,1])
print("특정 열만 뒤집기:\\n", arr_2d)

Reversed Array: [8 7 6 5 4 3 2 1]
전체 뒤집기:\n [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
행 단위 뒤집기:\n [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
열 단위 뒤집기:\n [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
특정 행만 뒤집기:\n [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
특정 열만 뒤집기:\n [[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [7]:
# CODE 셀 21
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("flatten:", x.flatten())

# flatten()은 깊은 복사(Copy)를 합니다.
a1 = x.flatten()
a1[0] = 99
print("x 원본 유지:\\n", x)
print("a1 변경됨:", a1)

# ravel()은 얕은 복사(View)를 합니다.
a2 = x.ravel()
a2[0] = 98
print("x 원본 변경됨:\\n", x)
print("a2 변경됨:", a2)

flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
x 원본 유지:\n [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a1 변경됨: [99  2  3  4  5  6  7  8  9 10 11 12]
x 원본 변경됨:\n [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a2 변경됨: [98  2  3  4  5  6  7  8  9 10 11 12]
